name: 'Packer build'
author: 'Robert Anderson <gelbander@gmail.com>'
description: 'Run packer build'
inputs:
  workingDir:
    description: 'Root directory'
    required: false
    default: '.'
  templateFileName:
    description: 'Packer template file eg "packer.json"'
    required: false
    default: 'packer.json'
  varList:
    description: 'Key value pair input'
    required: false
    default: ''
  varFileName:
    description: 'Var file to use for packer build'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'blue'